version: '3.9'

services:
  bwapp:
    image: raesene/bwapp
    container_name: bwapp
    restart: always
    ports:
      - "8080:80"
    networks:
      - bwapp_net

  nginx:
    image: owasp/modsecurity:nginx
    container_name: nginx_modsec
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw  # Ensure the file is writable
      - ./modsecurity-main.conf:/etc/nginx/modsecurity-main.conf:ro
      - ./modsecurity.conf:/etc/modsecurity/modsecurity.conf:ro
      - ./crs-setup.conf:/etc/modsecurity/crs-setup.conf:ro
      - ./rules/:/etc/modsecurity/rules/:ro
    depends_on:
      - bwapp
    networks:
      - bwapp_net

networks:
  bwapp_net:
    driver: bridge

